if(!exists("processed", mode="any")) source("C:/Users/Briggs/Desktop/R/retail/retail_data.r")

library(plyr)
library(neuralnet)
library(dplyr)
library(boot)

## Easy call variables for each 38 countries
Aussie <- subset(processed, processed$country == 'Australia')
austria <- subset(processed, processed$country == 'Austria')
bahrain <- subset(processed, processed$country == 'Bahrain')
belg <- subset(processed, processed$country == 'Belgium')
brazil <- subset(processed, processed$country =='Brazil')
canada <- subset(processed, processed$country =='Canada')
CI <- subset(processed, processed$country == 'Channel Islands')
cyprus <- subset(processed, processed$country == 'Cyprus')
CR <- subset(processed, processed$country == 'Czech Republic')
den <- subset(processed, processed$country == 'Denmark')
EIRE <- subset(processed, processed$country == 'EIRE')
EC <- subset(processed, processed$country == 'European Community')
finland <- subset(processed, processed$country == 'Finland')
France <- subset(processed, processed$country == 'France')
Germany <- subset(processed, processed$country == 'Germany')
greece <- subset(processed, processed$country == 'Greece')
ice <- subset(processed, processed$country == 'Iceland')
israel <- subset(processed, processed$country == 'Israel')
italy <- subset(processed, processed$country == 'Italy')
japan <- subset(processed, processed$country == 'Japan')
lebanon <- subset(processed, processed$country == 'Lebanon')
lithuania <- subset(processed, processed$country == 'Lithuania')
malta <- subset(processed, processed$country == 'Malta')
nether <- subset(processed, processed$country == 'Netherlands')
norway <- subset(processed, processed$country == 'Norway')
poland <- subset(processed, processed$country == 'Poland')
port <- subset(processed, processed$country == 'Portugal')
RSA <- subset(processed, processed$country == 'RSA')
SA <- subset(processed, processed$country == 'Saudi Arabia')
sing <- subset(processed, processed$country == 'Singapore')
spain <- subset(processed, processed$country == 'Spain')
sweden <- subset(processed, processed$country == 'Sweden')
Swiss <- subset(processed, processed$country == 'Switzerland')
AE <- subset(processed, processed$country == 'United Arab Emirates')
UK <- subset(processed, processed$country == 'United Kingdom')
un <- subset(processed, processed$country == 'Unspecified')
USA <- subset(processed, processed$country == 'USA')

## Putting countries into groups by area and number of sales
America <- dplyr::select(rbind(USA,canada,brazil),date,price)
NSF <- dplyr::select(rbind(norway,sweden,finland,den),date,price)
UAE <- dplyr::select(rbind(lebanon,israel,SA,AE,bahrain,cyprus),date,price)
Italy <- dplyr::select(rbind(greece,italy,malta,austria),date,price)
Spain <- dplyr::select(rbind(spain,port),date,price)
Poland <- dplyr::select(rbind(CR,poland,lithuania),date,price)
EIRE <- dplyr::select(rbind(EIRE,ice),date,price)
Japan <- dplyr::select(rbind(japan,sing),date,price)
Unspecified <- dplyr::select(rbind(un,EC),date,price)

